language: java

jdk:
  - openjdk11

before_script:
  - chmod +x gradlew

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build

    - stage: test
      script:
        - ./gradlew test

notifications:
  email:
    recipients:
      - tinghee0815@1utar.my
    on_success: always
    on_failure: always

